In [1]:
import numpy as np
import gymnasium as gym
from normalize_action import NormalizeAction
import bicycle_dengh
from stable_baselines3.common.vec_env import DummyVecEnv
from stable_baselines3.common.monitor import Monitor
from stable_baselines3 import PPO

In [ ]:
original_env = gym.make('BicycleDengh-v0', gui=False)

print(original_env.action_space.low)
for _ in range(10):
    print(original_env.action_space.sample())

In [2]:
env = NormalizeAction(gym.make('BicycleDengh-v0', gui=False))

print(env.action_space.low)

for _ in range(10):
    print(env.action_space.sample())

[-1. -1. -1.]
[-0.25421533  0.7855231   0.8175087 ]
[ 0.0752328   0.25200742 -0.44317475]
[-0.28553128 -0.5235834   0.92050296]
[ 0.6736036  0.9454488 -0.8173803]
[0.3300598  0.26457036 0.42570844]
[-0.5795435   0.08935115 -0.40020972]
[-0.43510795 -0.76349497 -0.7901347 ]
[ 0.11646766  0.57152355 -0.03261829]
[-0.62518394 -0.7807024   0.88019115]
[0.84658915 0.8704311  0.07711206]


In [2]:
normalized_env = gym.make('BicycleDengh-v0', gui=False)
# Note that we can use multiple wrappers
normalized_env = NormalizeAction(normalized_env)
# normalized_env = DummyVecEnv([lambda: normalized_env])
    
model = PPO(policy="MlpPolicy",
            env=env,
            n_steps=2048,
            batch_size=64,
            gae_lambda=0.98,
            gamma=0.99,
            n_epochs=4,
            ent_coef=0.01,
            # 0 for no output, 1 for info messages (such as device or wrappers used), 2 for debug messages
            verbose=0,
            )
model.learn(total_timesteps=100000,
            log_interval=1,)


KeyboardInterrupt: 